## Streszczenie {-}

Mapy wyborcze w Polsce ograniczają się w znacznej części do stosowania techniki kartogramów właściwych. Praca podejmuje się przeglądu alternatywnych technik wizualizacji przestrzennych - kartogramów geometrycznych oraz anamorfoz powierzchniowych. Techniki wizualizacji zostały przeanalizowane oraz porównane względem czytelności w celu znalezienia alternatyw dla kartogramu właściwego. W celu porównania technik została przeprowadzona ankiety - ich wyniki posłużyły do dalszej analizy. Praca została oparte o dane z wyborów prezydenckich w Polsce z 2020 roku, a do ich opracowania wykorzystano język programowania R. Wizualizacje kartograficzne zostały wygenerowane za pomocą pakietów cartogram oraz geogrid. Wyniki sugerują, że kartogramy geometryczne są najlepiej odbierane, kiedy są używane w celu oszacowania zjawiska ogółem, a kartogramy nieciągłe stanowią problem dla użytkowników. Kartodiagram Dorlinga jest nieodpowiedni dla danych względnych oraz zmiennych z wąskim zakresem wartości. W pracy nie udało się wyciągnąć jednoznacznych wniosków w kwestii anamorfoz ciągłych i sugerowana jest dalsza praca w tym podejmująca to zagadnienie.


Słowa kluczowe: kartogram geometryczny, mapy anamorficzne, anamorfoza ciągła, anamorfoza nieciągła, kartodiagram Dorlinga 

## Abstract {-}

Electoral maps in Poland are limited mainly to the use of the choropleth map technique. This paper reviews alternative techniques of spatial visualization - tile maps and cartograms. The visualization techniques are analyzed and compared in terms of readability in order to find an alternative to choropleth maps. In order to compare each technique, two surveys were conducted - their results were used for further analysis. The work was based on data from the 2020 presidential election in Poland, and the R programming language was used to prepare the data. Cartographic visualizations were generated using the cartogram and geogrid packages. The results suggest that tile maps are best received when used to estimate a phenomenon in general, while discontinuous cartograms are problematic for users. The Dorling cartogram is inappropriate for relative data and variables with a narrow range of values. The paper was unable to reach a clear conclusion on continuous cartograms, and further work is suggested on this topic.


Keywords: tile map, cartograms, contiguous cartogram, non-contiguous cartogram, Dorling cartogram


\newpage

\setstretch{1.2}\sf\tighttoc\doublespacing
